db:
  image: orchardup/mysql
  environment:
    MYSQL_USER: root
    MYSQL_PASSWORD: admin
    MYSQL_DATABASE: javatest
  ports:
    - "3306"

app:
  build: .
  links:
    - db:mysql
  ports:
    - "8080"


